/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BudgetUI;

import java.util.ArrayList;

/**
 *
 * @author melissacmitchell
 */

//computes the spending analysis data for display to the user
public class SpendingAnalysis extends javax.swing.JDialog {
    
    //transactions hold all the transactions from disk
    ArrayList<Transaction> transactions = null;
    
    //spending data 
    SpendingData spendingData = null;
    int yearToFilter = 0;

    /**
     * Creates new form SpendingAnalysis
     * @param parent
     * @param modal
     */
    public SpendingAnalysis(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        spendingData = new SpendingData();
        transactions = FileIO.readTransactions();
        yearToFilter = Integer.valueOf((String)jComboBoxYear.getSelectedItem());

        calculateSpendingAnalysis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonDone = new javax.swing.JButton();
        jPanelGeneral = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabelMonthlyAverage = new javax.swing.JLabel();
        jPanelCategory = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelKids = new javax.swing.JLabel();
        jLabelGroceries = new javax.swing.JLabel();
        jLabelDining = new javax.swing.JLabel();
        jLabelPersonal = new javax.swing.JLabel();
        jLabelEntertainment = new javax.swing.JLabel();
        jLabelGifts = new javax.swing.JLabel();
        jLabelHealth = new javax.swing.JLabel();
        jLabelMiscellaneous = new javax.swing.JLabel();
        jLabelBills = new javax.swing.JLabel();
        jLabelInvestments = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabelBillsPercentage = new javax.swing.JLabel();
        jLabelPersonalPercentage = new javax.swing.JLabel();
        jLabelHealthPercentage = new javax.swing.JLabel();
        jLabelEntertainmentPercentage = new javax.swing.JLabel();
        jLabelDiningPercentage = new javax.swing.JLabel();
        jLabelKidsPercentage = new javax.swing.JLabel();
        jLabelGroceriesPercentage = new javax.swing.JLabel();
        jLabelGiftsPercentage = new javax.swing.JLabel();
        jLabelMiscellaneousPercentage = new javax.swing.JLabel();
        jLabelInvestmentsPercentage = new javax.swing.JLabel();
        jPanelPrice = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25To50 = new javax.swing.JLabel();
        jLabel50To250 = new javax.swing.JLabel();
        jLabel250To500 = new javax.swing.JLabel();
        jLabel500To1000 = new javax.swing.JLabel();
        jLabelLessThan25 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel1000To2500 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabelOver2500 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxYear = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Annual Spending Analysis");

        jButtonDone.setText("Done");
        jButtonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoneActionPerformed(evt);
            }
        });

        jPanelGeneral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("General Information");

        jLabel9.setText("Monthly Average");

        jLabel10.setText("Total Amount Spent");

        jLabelTotal.setText("jLabel2");

        jLabelMonthlyAverage.setText("jLabel2");

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelGeneralLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMonthlyAverage, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanelGeneralLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMonthlyAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanelCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Category Analysis");

        jLabel12.setText("Bills and Utilities");

        jLabel13.setText("Kids");

        jLabel14.setText("Groceries");

        jLabel15.setText("Dining");

        jLabel16.setText("Miscellaneous");

        jLabel17.setText("Entertainment");

        jLabel18.setText("Personal Care");

        jLabel19.setText("Health and Fitness");

        jLabel20.setText("Gifts and Donations");

        jLabel21.setText("Investments");

        jLabelKids.setText("jLabel2");

        jLabelGroceries.setText("jLabel2");

        jLabelDining.setText("jLabel2");

        jLabelPersonal.setText("jLabel2");

        jLabelEntertainment.setText("jLabel2");

        jLabelGifts.setText("jLabel2");

        jLabelHealth.setText("jLabel2");

        jLabelMiscellaneous.setText("jLabel2");

        jLabelBills.setText("jLabel2");

        jLabelInvestments.setText("jLabel2");

        jLabel45.setText("Amount");

        jLabel46.setText("Percentage of Total");

        jLabelBillsPercentage.setText("jLabel2");

        jLabelPersonalPercentage.setText("jLabel2");

        jLabelHealthPercentage.setText("jLabel2");

        jLabelEntertainmentPercentage.setText("jLabel2");

        jLabelDiningPercentage.setText("jLabel2");

        jLabelKidsPercentage.setText("jLabel2");

        jLabelGroceriesPercentage.setText("jLabel2");

        jLabelGiftsPercentage.setText("jLabel2");

        jLabelMiscellaneousPercentage.setText("jLabel2");

        jLabelInvestmentsPercentage.setText("jLabel2");

        javax.swing.GroupLayout jPanelCategoryLayout = new javax.swing.GroupLayout(jPanelCategory);
        jPanelCategory.setLayout(jPanelCategoryLayout);
        jPanelCategoryLayout.setHorizontalGroup(
            jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryLayout.createSequentialGroup()
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel45)
                    .addGroup(jPanelCategoryLayout.createSequentialGroup()
                        .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelCategoryLayout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel7))
                                .addGroup(jPanelCategoryLayout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel19))))
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel17)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelKids)
                            .addComponent(jLabelMiscellaneous)
                            .addComponent(jLabelBills)
                            .addComponent(jLabelGifts)
                            .addComponent(jLabelHealth)
                            .addComponent(jLabelPersonal)
                            .addComponent(jLabelEntertainment)
                            .addComponent(jLabelGroceries)
                            .addComponent(jLabelDining)
                            .addComponent(jLabelInvestments))))
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCategoryLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jLabel46)
                        .addGap(23, 23, 23))
                    .addGroup(jPanelCategoryLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGroceriesPercentage)
                            .addComponent(jLabelBillsPercentage)
                            .addComponent(jLabelDiningPercentage)
                            .addComponent(jLabelKidsPercentage)
                            .addComponent(jLabelEntertainmentPercentage)
                            .addComponent(jLabelPersonalPercentage)
                            .addComponent(jLabelHealthPercentage)
                            .addComponent(jLabelMiscellaneousPercentage)
                            .addComponent(jLabelInvestmentsPercentage)
                            .addComponent(jLabelGiftsPercentage))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanelCategoryLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCategoryLayout.setVerticalGroup(
            jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(23, 23, 23)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46))
                .addGap(18, 18, 18)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabelBills, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBillsPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabelKids, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelKidsPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabelDining, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDiningPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabelGroceries, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGroceriesPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabelEntertainment, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEntertainmentPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabelPersonalPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabelHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHealthPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGifts, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabelGiftsPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabelInvestments, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInvestmentsPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabelMiscellaneous, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMiscellaneousPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanelPrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setText("Number of Payments in Each Price Range");

        jLabel22.setText("$0.01 - $25");

        jLabel23.setText("$25.01 - $50");

        jLabel24.setText("$50.01 - $250");

        jLabel25.setText("$250.01 - $500");

        jLabel26.setText("$500.01 - $1000");

        jLabel25To50.setText("jLabel2");

        jLabel50To250.setText("jLabel2");

        jLabel250To500.setText("jLabel2");

        jLabel500To1000.setText("jLabel2");

        jLabelLessThan25.setText("jLabel2");

        jLabel41.setText("$1000 - $2500");

        jLabel1000To2500.setText("jLabel2");

        jLabel43.setText("> $2500");

        jLabelOver2500.setText("jLabel2");

        javax.swing.GroupLayout jPanelPriceLayout = new javax.swing.GroupLayout(jPanelPrice);
        jPanelPrice.setLayout(jPanelPriceLayout);
        jPanelPriceLayout.setHorizontalGroup(
            jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPriceLayout.createSequentialGroup()
                .addGroup(jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPriceLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel6))
                    .addGroup(jPanelPriceLayout.createSequentialGroup()
                        .addGroup(jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPriceLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPriceLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(62, 62, 62)
                        .addGroup(jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25To50)
                            .addComponent(jLabelLessThan25)
                            .addComponent(jLabel50To250)
                            .addComponent(jLabel250To500)
                            .addComponent(jLabel500To1000)
                            .addComponent(jLabel1000To2500)
                            .addComponent(jLabelOver2500))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanelPriceLayout.setVerticalGroup(
            jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPriceLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addGroup(jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabelLessThan25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25To50, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50To250, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel250To500, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel500To1000, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel1000To2500, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabelOver2500, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("Year:");

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028" }));
        jComboBoxYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jButtonDone, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jButtonDone, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxYearActionPerformed
        
        //create a new spendingData
        spendingData = new SpendingData();
        
        //get the yearToFilter value from the combo box
        yearToFilter = Integer.valueOf((String)jComboBoxYear.getSelectedItem());
        
        //read transactions from disk
        transactions = FileIO.readTransactions();

        calculateSpendingAnalysis();
    }//GEN-LAST:event_jComboBoxYearActionPerformed

    private void jButtonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoneActionPerformed
        
        //close this dialog 
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDoneActionPerformed

    //calculates spending analysis based on the user's data
    private void calculateSpendingAnalysis() {

        for(Transaction transaction : transactions) {
            
            if (transaction.year != yearToFilter) {
                continue;
            }
            
            spendingData.totalAmountSpent += transaction.price * transaction.everyMonth;

            //Count the number of transactions in each price range
            if (transaction.price <= 25) 
                spendingData.numberLessThan25 +=1;
             
            else if (transaction.price <= 50) 
                spendingData.number25Through50 += 1;
             
            else if (transaction.price <= 250) 
                spendingData.number50Through250 += 1;
             
            else if (transaction.price <= 500) 
                spendingData.number250Through500 += 1;
                
            else if (transaction.price <= 1000) 
                spendingData.number500Through1000 += 1;
            
            else if (transaction.price <= 2500) 
                spendingData.number1000Through2500 += 1;
            
            else 
                spendingData.numberGreaterThan2500 += 1;
            
            
            if (null == transaction.category) 
                spendingData.costMiscellaneous += transaction.price;
            
            else //Calculate the amount spent in each category
            switch (transaction.category) {
                case BillsAndUtilities:
                    spendingData.costBills += transaction.price * transaction.everyMonth;
                    break;
                case Kids:
                    spendingData.costKids += transaction.price * transaction.everyMonth;
                    break;
                case Dining:
                    spendingData.costDining += transaction.price * transaction.everyMonth;
                    break;
                case Groceries:
                    spendingData.costGroceries += transaction.price * transaction.everyMonth;
                    break;
                case Entertainment:
                    spendingData.costEntertainment += transaction.price * transaction.everyMonth;
                    break;
                case PersonalCare:
                    spendingData.costPersonal += transaction.price * transaction.everyMonth;
                    break;
                case HealthAndFitness:
                    spendingData.costHealth += transaction.price * transaction.everyMonth;
                    break;
                case GiftsAndDonations:
                    spendingData.costGifts += transaction.price * transaction.everyMonth;
                    break;
                case Investments:
                    spendingData.costInvestments += transaction.price * transaction.everyMonth;
                    break;
                default:
                    spendingData.costMiscellaneous += transaction.price * transaction.everyMonth;
                    break;
            }
        }
            
        updateUI();
    }
    
    
    private void updateUI() {
        //display the spending analysis data
        //display overall spending analysis
        jLabelTotal.setText("$" + String.format("%,.2f", spendingData.totalAmountSpent));
        jLabelMonthlyAverage.setText("$" + String.format("%,.2f", spendingData.totalAmountSpent/12));
        
        //display price analysis
        jLabelLessThan25.setText(String.valueOf(spendingData.numberLessThan25));
        jLabel25To50.setText(String.valueOf(spendingData.number25Through50));
        jLabel50To250.setText(String.valueOf(spendingData.number50Through250));
        jLabel250To500.setText(String.valueOf(spendingData.number250Through500));
        jLabel500To1000.setText(String.valueOf(spendingData.number500Through1000));
        jLabel1000To2500.setText(String.valueOf(spendingData.number1000Through2500));
        jLabelOver2500.setText(String.valueOf(spendingData.numberGreaterThan2500));
        
        //display category analysis
        //total in each category
        jLabelBills.setText("$" + String.format("%,.2f", spendingData.costBills));
        jLabelKids.setText("$" + String.format("%,.2f", spendingData.costKids));
        jLabelDining.setText("$" + String.format("%,.2f", spendingData.costDining));
        jLabelGroceries.setText("$" + String.format("%,.2f", spendingData.costGroceries));
        jLabelEntertainment.setText("$" + String.format("%,.2f", spendingData.costEntertainment));
        jLabelPersonal.setText("$" + String.format("%,.2f", spendingData.costPersonal));
        jLabelHealth.setText("$" + String.format("%,.2f", spendingData.costHealth));
        jLabelGifts.setText("$" + String.format("%,.2f", spendingData.costGifts));
        jLabelInvestments.setText("$" + String.format("%,.2f", spendingData.costInvestments));
        jLabelMiscellaneous.setText("$" + String.format("%,.2f", spendingData.costMiscellaneous));
        
        //percentage of total spending for each category
        if (spendingData.totalAmountSpent != 0) {
            jLabelBillsPercentage.setText(String.format("%,.2f", (spendingData.costBills/spendingData.totalAmountSpent) * 100) + "%");
            jLabelKidsPercentage.setText(String.format("%,.2f", (spendingData.costKids/spendingData.totalAmountSpent) * 100) + "%");
            jLabelDiningPercentage.setText(String.format("%,.2f", (spendingData.costDining/spendingData.totalAmountSpent) * 100) + "%");
            jLabelGroceriesPercentage.setText(String.format("%,.2f", (spendingData.costGroceries/spendingData.totalAmountSpent) * 100) + "%");
            jLabelEntertainmentPercentage.setText(String.format("%,.2f", (spendingData.costEntertainment/spendingData.totalAmountSpent) * 100) + "%");
            jLabelPersonalPercentage.setText(String.format("%,.2f", (spendingData.costPersonal/spendingData.totalAmountSpent) * 100) + "%");
            jLabelHealthPercentage.setText(String.format("%,.2f", (spendingData.costHealth/spendingData.totalAmountSpent) * 100) + "%");
            jLabelGiftsPercentage.setText(String.format("%,.2f", (spendingData.costGifts/spendingData.totalAmountSpent) * 100) + "%");
            jLabelInvestmentsPercentage.setText(String.format("%,.2f", (spendingData.costInvestments/spendingData.totalAmountSpent) * 100) + "%");
            jLabelMiscellaneousPercentage.setText(String.format("%,.2f", (spendingData.costMiscellaneous/spendingData.totalAmountSpent) * 100) + "%");
        } else {
            //set percentage to 0 if no transactions have been added
            jLabelBillsPercentage.setText("0.00%");
            jLabelKidsPercentage.setText("0.00%");
            jLabelDiningPercentage.setText("0.00%");
            jLabelGroceriesPercentage.setText("0.00%");
            jLabelEntertainmentPercentage.setText("0.00%");
            jLabelPersonalPercentage.setText("0.00%");
            jLabelHealthPercentage.setText("0.00%");
            jLabelGiftsPercentage.setText("0.00%");
            jLabelInvestmentsPercentage.setText("0.00%");
            jLabelMiscellaneousPercentage.setText("0.00%");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpendingAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpendingAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpendingAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpendingAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SpendingAnalysis dialog = new SpendingAnalysis(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDone;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel1000To2500;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel250To500;
    private javax.swing.JLabel jLabel25To50;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel500To1000;
    private javax.swing.JLabel jLabel50To250;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBills;
    private javax.swing.JLabel jLabelBillsPercentage;
    private javax.swing.JLabel jLabelDining;
    private javax.swing.JLabel jLabelDiningPercentage;
    private javax.swing.JLabel jLabelEntertainment;
    private javax.swing.JLabel jLabelEntertainmentPercentage;
    private javax.swing.JLabel jLabelGifts;
    private javax.swing.JLabel jLabelGiftsPercentage;
    private javax.swing.JLabel jLabelGroceries;
    private javax.swing.JLabel jLabelGroceriesPercentage;
    private javax.swing.JLabel jLabelHealth;
    private javax.swing.JLabel jLabelHealthPercentage;
    private javax.swing.JLabel jLabelInvestments;
    private javax.swing.JLabel jLabelInvestmentsPercentage;
    private javax.swing.JLabel jLabelKids;
    private javax.swing.JLabel jLabelKidsPercentage;
    private javax.swing.JLabel jLabelLessThan25;
    private javax.swing.JLabel jLabelMiscellaneous;
    private javax.swing.JLabel jLabelMiscellaneousPercentage;
    private javax.swing.JLabel jLabelMonthlyAverage;
    private javax.swing.JLabel jLabelOver2500;
    private javax.swing.JLabel jLabelPersonal;
    private javax.swing.JLabel jLabelPersonalPercentage;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanelCategory;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelPrice;
    // End of variables declaration//GEN-END:variables
}
